### ISSUE TITLE
Statamic 4 modal positioning

### ISSUE THREAD

**Issue by webguy-nz** [stack83com/statamic-chatgpt-integration#4]
In Statamic 4, when opening the ChatGPT window, the modal dialog positions relative to the parent element it is in. For example, I have the button in the sidebar and the modal dialog positions fixed to the top left corner of the sidebar.

![image](https://github.com/stack83com/statamic-chatgpt-integration/assets/2226353/153158d2-9e1f-4b85-9047-8480d77a92a6)

I have tried adjusting the css in the OpenChat.vue component, but my knowledge of Statamic does not stretch this far.

**Comment by djmenkveld** [comment]
Hi Scott, we will push a fix asap.

**Comment by webguy-nz** [comment]
Any update on this?

**Comment by gokoppa-user** [comment]
@webguy-nz This issue should be solved, just pull the latest release.

**Comment by djmenkveld** [comment]
@webguy-nz This issue should be solved, you can pull the latest release.
